### ISSUE TITLE
.NET version support

### ISSUE THREAD

**Issue by Liam3851** [Refinitiv-API-Samples/Article.EikonDataAPI.DotNet.Library#1]
The readme says this supports .NET 4.5 through 4.6.1. Do higher versions of .NET (4.6.2 through 4.8) not function, or are they just untested at this time? The package does appear in NuGet under 4.6.2, for example.

**Comment by jirapongse-refinitiv** [comment]
They are just untested at that time. 
I have run a quick test with 4.7.2 and it works fine.

**Comment by Liam3851** [comment]
Got it. Thanks!
